name: Lay Eggs

on:
  schedule:
    # Runs every 250 minutes starting at 9:20 AM UTC
    - cron: "20 9,13,17,21 * * *"
  workflow_dispatch:

jobs:
  run-script:
    name: Foundry Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Lay Eggs
        env:
          BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
          BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          forge script LayEggs -vvv --rpc-url $BASE_SEPOLIA_RPC_URL --etherscan-api-key $BASESCAN_API_KEY --private-key $PRIVATE_KEY --broadcast
