name: Lay Eggs

on:
  schedule:
    # Runs every 125 minutes starting at 9:20 AM UTC
    - cron: "20 9,11,13,15,17,19,21,23,1,3,5,7 * * *"
  workflow_dispatch:

jobs:
  run-script:
    name: Lay Eggs
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Bun"
        uses: "oven-sh/setup-bun@v1"

      - name: "Install the Node.js dependencies"
        run: "bun install"

      - name: Run Lay Eggs
        env:
          BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
          BASESCAN_API_KEY: ${{ secrets.BASESCAN_API_KEY }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          forge script LayEggs -vvv --rpc-url $BASE_SEPOLIA_RPC_URL --etherscan-api-key $BASESCAN_API_KEY --private-key $PRIVATE_KEY --broadcast
